.TH MADPLAY 1 11-Sep-2000 MAD
.SH NAME
madplay \- decode and play MPEG audio stream(s)
.SH SYNOPSIS
madplay
.RB [ -v | -q | -Q ]
.RB [ -m | -1 | -2 ]
.RB [ -d ]
.RB [ -o
.RI [ type :] file.out ]
.I file.mpg
[...]
.SH DESCRIPTION
.B madplay
is a command-line front-end to the
.I MAD
library.
.PP
.I MAD
is an MPEG audio decoder. It currently supports MPEG 1 as well as the MPEG 2
extension to Lower Sampling Frequencies. All three audio layers (Layer I,
Layer II, and Layer III aka MP3) are fully implemented.
.PP
.I MAD
does not yet support MPEG 2 multichannel audio (although it should be backward
compatible with such streams), nor does it support the so-called MPEG 2.5
format.
.PP
By default
.B
madplay
reads and decodes one or more input files containing MPEG audio data, and
plays them on the native audio device. If the input file is a single dash
(\-), data is read from stdin.
.SH OPTIONS
.TP
-v
Show information about the stream during decoding, including playing time,
audio layer, bitrate, sampling frequency, and stereo mode.
.TP
-q
Do not show any information during decoding, except warnings.
.TP
-Q
Do not show any information during decoding, including warnings.
.TP
-m
Mix the left and right channels to produce monaural output.
.TP
-1
Output the first (left) channel only.
.TP
-2
Output the second (right) channel only.
.TP
-d
Do not dither the output PCM samples.
.TP
-o
Direct the output to the specified location, rather than playing the audio on
the native audio device. The format of the output can be specified by the
given
.I type
which can be any of the supported output formats (see below.) Alternatively,
if a format is not specified, one will be inferred from the specified output
filename. If the filename is a single dash (\-), the output will be written to
stdout.
.SH OUTPUT FORMATS
Other than playing on the native audio device, the following output formats
are also supported:
.TP
RAW
binary signed 16-bit little-endian linear PCM, stereo interleaved
.TP
WAVE
Microsoft RIFF/WAVE, 16-bit PCM format
.TP
HEX
hexadecimal signed 24-bit linear PCM, stereo interleaved, one sample per
output line (debug builds only)
.TP
NULL
no output (usually for testing or timing the decoder)
.SH NOTES
Because
.I MAD
produces output samples with a precision greater than 24 bits, by default
.B madplay
will dither the output to the necessary number of bits, usually 16. This
produces high quality audio that generally sounds superior to using a simple
rounding approach. However, dithering may unfavorably affect an analytic
examination of the output, and therefore it may be disabled by using the \-d
option.
.PP
.I MAD
is implemented entirely without the use of floating point arithmetic and
should therefore perform well on all architectures, especially those without
an FPU.
.SH AUTHOR
Robert Leslie <rob@mars.org>
