/* Automatically generated by po2tbl.sed from mad.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Copyright (C)", 2},
  {"MPEG Audio Decoder", 3},
  {"\
This program is free software; you can redistribute it and/or modify it\n\
under the terms of the GNU General Public License as published by the\n\
Free Software Foundation; either version 2 of the License, or (at your\n\
option) any later version.\n\
\n\
This program is distributed in the hope that it will be useful, but\n\
WITHOUT ANY WARRANTY; without even the implied warranty of\n\
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n\
General Public License for more details.\n\
\n\
You should have received a copy of the GNU General Public License along\n\
with this program; if not, write to the Free Software Foundation, Inc.,\n\
59 Temple Place, Suite 330, Boston, MA 02111-1307 USA\n\
\n\
If you would like to negotiate alternate licensing terms, you may do so\n\
by contacting the author: %s <%s>\n", 4},
  {"%s: option `%s' is ambiguous\n", 5},
  {"%s: option `--%s' doesn't allow an argument\n", 6},
  {"%s: option `%c%s' doesn't allow an argument\n", 7},
  {"%s: option `%s' requires an argument\n", 8},
  {"%s: unrecognized option `--%s'\n", 9},
  {"%s: unrecognized option `%c%s'\n", 10},
  {"%s: illegal option -- %c\n", 11},
  {"%s: invalid option -- %c\n", 12},
  {"%s: option requires an argument -- %c\n", 13},
  {"%s: option `-W %s' is ambiguous\n", 14},
  {"%s: option `-W %s' doesn't allow an argument\n", 15},
  {"Usage: %s [OPTIONS] FILE [...]\n", 16},
  {"Try `%s --help' for more information.\n", 17},
  {"Decode and play MPEG audio FILE(s).\n", 18},
  {"\
\n\
Verbosity:\n", 19},
  {"  -v, --verbose              show status while decoding\n", 20},
  {"  -q, --quiet                be quiet but show warnings\n", 21},
  {"  -Q, --very-quiet           be quiet and do not show warnings\n", 22},
  {"\
\n\
Audio output:\n", 23},
  {"\
  -o, --output=[TYPE:]PATH   send output to PATH with format TYPE (see \
below)\n", 24},
  {"  -d, --no-dither            do not dither output PCM samples\n", 25},
  {"      --downsample           reduce output sample rate 2:1\n", 26},
  {"      --fade-in[=DURATION]   fade-in songs over DURATION (default %s)\n", 27},
  {"\
      --fade-out[=DURATION]  fade-out songs over DURATION (default %s)\n", 28},
  {"  -g, --gap=DURATION         set inter-song gap to DURATION\n", 29},
  {"  -x, --cross-fade           cross-fade songs (use with negative gap)\n", 30},
  {"  -a, --attenuate=DECIBELS   attenuate signal by DECIBELS (-)\n", 31},
  {"  -a, --amplify=DECIBELS     amplify signal by DECIBELS (+)\n", 32},
  {"\
\n\
Channel selection:\n", 33},
  {"  -1, --left                 output first (left) channel only\n", 34},
  {"  -2, --right                output second (right) channel only\n", 35},
  {"\
  -m, --mono                 mix left and right channels for monaural \
output\n", 36},
  {"  -S, --stereo               force stereo output\n", 37},
  {"\
\n\
Experimental:\n", 38},
  {"\
      --external-mix         output pre-synthesis samples for external \
mixer\n", 39},
  {"      --experimental         enable experimental filter\n", 40},
  {"\
\n\
Playback:\n", 41},
  {"  -s, --start=TIME           skip to begin at TIME (HH:MM:SS.DDD)\n", 42},
  {"  -t, --time=DURATION        play only for DURATION (HH:MM:SS.DDD)\n", 43},
  {"  -z, --shuffle              randomize file list\n", 44},
  {"  -r, --repeat[=MAX]         play files MAX times, or indefinitely\n", 45},
  {"      --tty-control          enable keyboard controls\n", 46},
  {"      --no-tty-control       do not enable keyboard controls\n", 47},
  {"\
\n\
Miscellaneous:\n", 48},
  {"  -V, --version              display version number and exit\n", 49},
  {"      --license              show copyright/license message and exit\n", 50},
  {"  -h, --help                 display this help and exit\n", 51},
  {"\
\n\
Supported output format types:\n", 52},
  {"  raw     binary signed 16-bit host-endian linear PCM\n", 53},
  {"  wave    Microsoft RIFF/WAVE, 16-bit PCM format (*.wav)\n", 54},
  {"  snd     Sun/NeXT audio, 8-bit ISDN mu-law (*.au, *.snd)\n", 55},
  {"  hex     hexadecimal signed 24-bit linear PCM\n", 56},
  {"  null    no output (decode only)\n", 57},
  {"invalid %s specification \"%s\"", 58},
  {"%s must be positive", 59},
  {"invalid decibel specification \"%s\"", 60},
  {"decibel value must be in the range %+d to %+d", 61},
  {"gap time", 62},
  {"fade-in time", 63},
  {"multiple output destinations not supported", 64},
  {"unknown output format type for \"%s\"", 65},
  {"fade-out time", 66},
  {"invalid repeat count \"%s\"", 67},
  {"start time", 68},
  {"playing time", 69},
  {"`%s --license' for licensing information.\n", 70},
  {"Build options: %s\n", 71},
  {"cross-fade ignored without gap", 72},
  {"cross-fade ignored without negative gap", 73},
  {"%s: Not a regular file\n", 74},
  {"%8.1f MB  %c%3u kbps  %s  %s\n", 75},
  {"Usage: %s [-s] FILE [...]\n", 76},
  {"TOTAL", 77},
  {"Usage: %s input1 [input2 ...]\n", 78},
  {"%s: unknown output format type", 79},
  {"not enough memory to allocate mixing buffers", 80},
  {"mixing %d streams\n", 81},
  {"Title", 82},
  {"Composer", 83},
  {"Artist", 84},
  {"Orchestra", 85},
  {"Conductor", 86},
  {"Lyricist", 87},
  {"Album", 88},
  {"Year", 89},
  {"Track", 90},
  {"Genre", 91},
  {"Encoder", 92},
  {"Produced (P)", 93},
  {"not enough memory to display tag", 94},
  {"I", 95},
  {"II", 96},
  {"III", 97},
  {"single channel", 98},
  {"dual channel", 99},
  {"joint stereo", 100},
  {"stereo", 101},
  {" (LR)", 102},
  {" (MS)", 103},
  {" (I)", 104},
  {" (MS+I)", 105},
  {"%s Layer %s, %s%u kbps%s, %u Hz, %s%s, %s", 106},
  {"VBR (avg ", 107},
  {")", 108},
  {"CRC", 109},
  {"no CRC", 110},
  {"no channel selected for dual channel; using first", 111},
  {"using output sample frequency %u Hz", 112},
  {"mono output not available; forcing stereo", 113},
  {"stereo output not available; using first channel (use -m to mix)", 114},
  {"sample frequency %u Hz not available; closest %u Hz", 115},
  {"not enough memory to allocate resampling buffer", 116},
  {"cannot resample %u Hz to %u Hz", 117},
  {"resampling %u Hz to %u Hz", 118},
  {"not enough memory to allocate tag data buffer", 119},
  {"EOF while reading tag data", 120},
  {"not enough memory", 121},
  {"lost synchronization", 122},
  {"reserved header layer value", 123},
  {"forbidden bitrate value", 124},
  {"reserved sample frequency value", 125},
  {"reserved emphasis value", 126},
  {"CRC check failed", 127},
  {"forbidden bit allocation value", 128},
  {"bad scalefactor index", 129},
  {"bad frame length", 130},
  {"bad big_values count", 131},
  {"reserved block_type", 132},
  {"bad scalefactor selection info", 133},
  {"bad main_data_begin pointer", 134},
  {"bad audio data length", 135},
  {"bad Huffman table select", 136},
  {"Huffman data overrun", 137},
  {"incompatible block_type for JS", 138},
  {"frame %lu: %s", 139},
  {"not enough memory to allocate input buffer", 140},
  {"stdin", 141},
  {"is a tty", 142},
  {"%lu frames decoded (%s), %+.1f dB peak amplitude, %lu clipped samples\n", 143},
  {"Paused", 144},
  {"Stopped", 145},
  {"[Overall Time]", 146},
  {"[Current Time Remaining]", 147},
  {"[Current Time]", 148},
  {"not enough memory to allocate sample buffer", 149},
  {"not enough memory to allocate filters", 150},
  {"lead-in", 151},
  {"no supported audio format available", 152},
  {"error getting error text", 153},
  {"failed to create synchronization object", 154},
  {"wait abandoned", 155},
  {"wait timeout", 156},
  {"wait failed", 157},
  {"failed to close synchronization object", 158},
};

int _msg_tbl_length = 158;
